# For more information about the available options please visit: http://go/backstage (VPN required)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: unity/python-sdk-samples
  name: python-sdk-samples
  description: "Various samples that show how to use the Unity Cloud Python SDK."
  labels:
    costcenter: "7054"
  links:
    - url: https://unity.slack.com/messages/C04R01SGG68/
      title: "#uc-cs-am-python-sdk"
      icon: chat
spec:
  type: other
  lifecycle: experimental
  owner: unity/digital-twins-sdk-admins
